version: '3'

services:
  nodeprisma:
    image: postgres
    environment:
      POSTGRES_DB: go-hex
      POSTGRES_PASSWORD: testpass123
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - S:\Project\api\storage/:/var/lib/postgresql/data/